# Generated by Django 5.2 on 2025-04-24 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('onboarded_at', models.DateTimeField()),
                ('profile_pic_url', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSku',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_url', models.CharField(max_length=255)),
                ('parentage', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('mfn_sku', models.CharField(max_length=100)),
                ('case_quantity', models.IntegerField()),
                ('upc_gtin', models.CharField(max_length=50)),
                ('asin', models.CharField(max_length=50)),
                ('epic_purchase_cost', models.JSONField(blank=True, null=True)),
                ('contracted_sell_price', models.JSONField(blank=True, null=True)),
                ('retail_price', models.JSONField(blank=True, null=True)),
                ('lead_time', models.JSONField(blank=True, null=True)),
                ('weight', models.JSONField(blank=True, null=True)),
                ('dimensions', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_skus', to='product_management.brand')),
            ],
        ),
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('epic_sku_id', models.CharField(max_length=100)),
                ('marketplace', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('epic_status', models.CharField(max_length=50)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('product_sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='product_management.productsku')),
            ],
        ),
    ]
